<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $countries = [
            ['nationality_name_ar'=>'ليبي','nationality_name_en'=>'Libyan','country_name_ar'=>'ليبيا','country_name_en'=>'Libya','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فلسطيني','nationality_name_en'=>'Palestinian','country_name_ar'=>'فلسطين','country_name_en'=>'Palestine','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أفغاني','nationality_name_en'=>'Afghan','country_name_ar'=>'أفغانستان','country_name_en'=>'Afghanistan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ألباني','nationality_name_en'=>'Albanian','country_name_ar'=>'ألبانيا','country_name_en'=>'Albania','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'جزائري','nationality_name_en'=>'Algerian','country_name_ar'=>'الجزائر','country_name_en'=>'Algeria','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أندوري','nationality_name_en'=>'Andorran','country_name_ar'=>'أندورا','country_name_en'=>'Andorra','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أنغولي','nationality_name_en'=>'Angolan','country_name_ar'=>'أنغولا','country_name_en'=>'Angola','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أنتيغوي','nationality_name_en'=>'Antiguan','country_name_ar'=>'أنتيغوا وبربودا','country_name_en'=>'Antigua and Barbuda','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أرجنتيني','nationality_name_en'=>'Argentine','country_name_ar'=>'الأرجنتين','country_name_en'=>'Argentina','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أرميني','nationality_name_en'=>'Armenian','country_name_ar'=>'أرمينيا','country_name_en'=>'Armenia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أسترالي','nationality_name_en'=>'Australian','country_name_ar'=>'أستراليا','country_name_en'=>'Australia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'نمساوي','nationality_name_en'=>'Austrian','country_name_ar'=>'النمسا','country_name_en'=>'Austria','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أذربيجاني','nationality_name_en'=>'Azerbaijani','country_name_ar'=>'أذربيجان','country_name_en'=>'Azerbaijan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بهامي','nationality_name_en'=>'Bahamian','country_name_ar'=>'البهاما','country_name_en'=>'Bahamas','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بحريني','nationality_name_en'=>'Bahraini','country_name_ar'=>'البحرين','country_name_en'=>'Bahrain','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بنغلاديشي','nationality_name_en'=>'Bangladeshi','country_name_ar'=>'بنغلاديش','country_name_en'=>'Bangladesh','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بربادوسي','nationality_name_en'=>'Barbadian','country_name_ar'=>'بربادوس','country_name_en'=>'Barbados','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بيلاروسي','nationality_name_en'=>'Belarusian','country_name_ar'=>'بيلاروس','country_name_en'=>'Belarus','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بلجيكي','nationality_name_en'=>'Belgian','country_name_ar'=>'بلجيكا','country_name_en'=>'Belgium','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بليزي','nationality_name_en'=>'Belizean','country_name_ar'=>'بليز','country_name_en'=>'Belize','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بنيني','nationality_name_en'=>'Beninese','country_name_ar'=>'بنين','country_name_en'=>'Benin','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بوتاني','nationality_name_en'=>'Bhutanese','country_name_ar'=>'بوتان','country_name_en'=>'Bhutan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بوليفي','nationality_name_en'=>'Bolivian','country_name_ar'=>'بوليفيا','country_name_en'=>'Bolivia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بوسني','nationality_name_en'=>'Bosnian','country_name_ar'=>'البوسنة والهرسك','country_name_en'=>'Bosnia and Herzegovina','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بوتسواني','nationality_name_en'=>'Botswanan','country_name_ar'=>'بوتسوانا','country_name_en'=>'Botswana','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'برازيلي','nationality_name_en'=>'Brazilian','country_name_ar'=>'البرازيل','country_name_en'=>'Brazil','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بروناوي','nationality_name_en'=>'Bruneian','country_name_ar'=>'بروناي','country_name_en'=>'Brunei','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بلغاري','nationality_name_en'=>'Bulgarian','country_name_ar'=>'بلغاريا','country_name_en'=>'Bulgaria','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بوركيني','nationality_name_en'=>'Burkinabé','country_name_ar'=>'بوركينا فاسو','country_name_en'=>'Burkina Faso','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بوروندي','nationality_name_en'=>'Burundian','country_name_ar'=>'بوروندي','country_name_en'=>'Burundi','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'رأس أخضري','nationality_name_en'=>'Cape Verdean','country_name_ar'=>'الرأس الأخضر','country_name_en'=>'Cabo Verde','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كمبودي','nationality_name_en'=>'Cambodian','country_name_ar'=>'كمبوديا','country_name_en'=>'Cambodia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كاميروني','nationality_name_en'=>'Cameroonian','country_name_ar'=>'الكاميرون','country_name_en'=>'Cameroon','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كندي','nationality_name_en'=>'Canadian','country_name_ar'=>'كندا','country_name_en'=>'Canada','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أفريقي وسطي','nationality_name_en'=>'Central African','country_name_ar'=>'جمهورية أفريقيا الوسطى','country_name_en'=>'Central African Republic','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تشادي','nationality_name_en'=>'Chadian','country_name_ar'=>'تشاد','country_name_en'=>'Chad','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تشيلي','nationality_name_en'=>'Chilean','country_name_ar'=>'تشيلي','country_name_en'=>'Chile','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'صيني','nationality_name_en'=>'Chinese','country_name_ar'=>'الصين','country_name_en'=>'China','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كولومبي','nationality_name_en'=>'Colombian','country_name_ar'=>'كولومبيا','country_name_en'=>'Colombia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'قمري','nationality_name_en'=>'Comorian','country_name_ar'=>'جزر القمر','country_name_en'=>'Comoros','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كونغولي','nationality_name_en'=>'Congolese','country_name_ar'=>'جمهورية الكونغو','country_name_en'=>'Congo','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كونغولي ديمقراطي','nationality_name_en'=>'Congolese','country_name_ar'=>'جمهورية الكونغو الديمقراطية','country_name_en'=>'Democratic Republic of the Congo','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كوستاريكي','nationality_name_en'=>'Costa Rican','country_name_ar'=>'كوستاريكا','country_name_en'=>'Costa Rica','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'عاجي','nationality_name_en'=>'Ivorian','country_name_ar'=>'ساحل العاج','country_name_en'=>"Côte d'Ivoire",'created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كرواتي','nationality_name_en'=>'Croatian','country_name_ar'=>'كرواتيا','country_name_en'=>'Croatia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كوبي','nationality_name_en'=>'Cuban','country_name_ar'=>'كوبا','country_name_en'=>'Cuba','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'قبرصي','nationality_name_en'=>'Cypriot','country_name_ar'=>'قبرص','country_name_en'=>'Cyprus','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تشيكي','nationality_name_en'=>'Czech','country_name_ar'=>'التشيك','country_name_en'=>'Czech Republic','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'دنماركي','nationality_name_en'=>'Danish','country_name_ar'=>'الدنمارك','country_name_en'=>'Denmark','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'جيبوتي','nationality_name_en'=>'Djiboutian','country_name_ar'=>'جيبوتي','country_name_en'=>'Djibouti','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'دومينيكي','nationality_name_en'=>'Dominican','country_name_ar'=>'دومينيكا','country_name_en'=>'Dominica','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'دومينيكاني','nationality_name_en'=>'Dominican','country_name_ar'=>'جمهورية الدومينيكان','country_name_en'=>'Dominican Republic','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إكوادوري','nationality_name_en'=>'Ecuadorian','country_name_ar'=>'الإكوادور','country_name_en'=>'Ecuador','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مصري','nationality_name_en'=>'Egyptian','country_name_ar'=>'مصر','country_name_en'=>'Egypt','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سلفادوري','nationality_name_en'=>'Salvadoran','country_name_ar'=>'السلفادور','country_name_en'=>'El Salvador','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'غيني استوائي','nationality_name_en'=>'Equatorial Guinean','country_name_ar'=>'غينيا الاستوائية','country_name_en'=>'Equatorial Guinea','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إريتري','nationality_name_en'=>'Eritrean','country_name_ar'=>'إريتريا','country_name_en'=>'Eritrea','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إستوني','nationality_name_en'=>'Estonian','country_name_ar'=>'إستونيا','country_name_en'=>'Estonia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إسواتيني','nationality_name_en'=>'Eswatini','country_name_ar'=>'إسواتيني','country_name_en'=>'Eswatini','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إثيوبي','nationality_name_en'=>'Ethiopian','country_name_ar'=>'إثيوبيا','country_name_en'=>'Ethiopia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فيجياني','nationality_name_en'=>'Fijian','country_name_ar'=>'فيجي','country_name_en'=>'Fiji','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فنلندي','nationality_name_en'=>'Finnish','country_name_ar'=>'فنلندا','country_name_en'=>'Finland','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فرنسي','nationality_name_en'=>'French','country_name_ar'=>'فرنسا','country_name_en'=>'France','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'غابوني','nationality_name_en'=>'Gabonese','country_name_ar'=>'الغابون','country_name_en'=>'Gabon','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'غامبي','nationality_name_en'=>'Gambian','country_name_ar'=>'غامبيا','country_name_en'=>'Gambia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'جورجي','nationality_name_en'=>'Georgian','country_name_ar'=>'جورجيا','country_name_en'=>'Georgia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ألماني','nationality_name_en'=>'German','country_name_ar'=>'ألمانيا','country_name_en'=>'Germany','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'غاني','nationality_name_en'=>'Ghanaian','country_name_ar'=>'غانا','country_name_en'=>'Ghana','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'يوناني','nationality_name_en'=>'Greek','country_name_ar'=>'اليونان','country_name_en'=>'Greece','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'غرينادي','nationality_name_en'=>'Grenadian','country_name_ar'=>'غرينادا','country_name_en'=>'Grenada','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'غواتيمالي','nationality_name_en'=>'Guatemalan','country_name_ar'=>'غواتيمالا','country_name_en'=>'Guatemala','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'غيني','nationality_name_en'=>'Guinean','country_name_ar'=>'غينيا','country_name_en'=>'Guinea','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بيساوي','nationality_name_en'=>'Bissau-Guinean','country_name_ar'=>'غينيا بيساو','country_name_en'=>'Guinea-Bissau','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'غياني','nationality_name_en'=>'Guyanese','country_name_ar'=>'غيانا','country_name_en'=>'Guyana','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'هايتي','nationality_name_en'=>'Haitian','country_name_ar'=>'هايتي','country_name_en'=>'Haiti','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'هندوراسي','nationality_name_en'=>'Honduran','country_name_ar'=>'هندوراس','country_name_en'=>'Honduras','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مجري','nationality_name_en'=>'Hungarian','country_name_ar'=>'المجر','country_name_en'=>'Hungary','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'آيسلندي','nationality_name_en'=>'Icelandic','country_name_ar'=>'آيسلندا','country_name_en'=>'Iceland','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'هندي','nationality_name_en'=>'Indian','country_name_ar'=>'الهند','country_name_en'=>'India','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إندونيسي','nationality_name_en'=>'Indonesian','country_name_ar'=>'إندونيسيا','country_name_en'=>'Indonesia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إيراني','nationality_name_en'=>'Iranian','country_name_ar'=>'إيران','country_name_en'=>'Iran','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'عراقي','nationality_name_en'=>'Iraqi','country_name_ar'=>'العراق','country_name_en'=>'Iraq','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أيرلندي','nationality_name_en'=>'Irish','country_name_ar'=>'أيرلندا','country_name_en'=>'Ireland','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إسرائيلي','nationality_name_en'=>'Israeli','country_name_ar'=>'إسرائيل','country_name_en'=>'Israel','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إيطالي','nationality_name_en'=>'Italian','country_name_ar'=>'إيطاليا','country_name_en'=>'Italy','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'جامايكي','nationality_name_en'=>'Jamaican','country_name_ar'=>'جامايكا','country_name_en'=>'Jamaica','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ياباني','nationality_name_en'=>'Japanese','country_name_ar'=>'اليابان','country_name_en'=>'Japan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أردني','nationality_name_en'=>'Jordanian','country_name_ar'=>'الأردن','country_name_en'=>'Jordan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كازاخستاني','nationality_name_en'=>'Kazakhstani','country_name_ar'=>'كازاخستان','country_name_en'=>'Kazakhstan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كيني','nationality_name_en'=>'Kenyan','country_name_ar'=>'كينيا','country_name_en'=>'Kenya','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كيريباتي','nationality_name_en'=>'Kiribati','country_name_ar'=>'كيريباتي','country_name_en'=>'Kiribati','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كويتي','nationality_name_en'=>'Kuwaiti','country_name_ar'=>'الكويت','country_name_en'=>'Kuwait','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'قيرغيزي','nationality_name_en'=>'Kyrgyzstani','country_name_ar'=>'قيرغيزستان','country_name_en'=>'Kyrgyzstan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'لاوسي','nationality_name_en'=>'Lao','country_name_ar'=>'لاوس','country_name_en'=>'Laos','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'لاتفي','nationality_name_en'=>'Latvian','country_name_ar'=>'لاتفيا','country_name_en'=>'Latvia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'لبناني','nationality_name_en'=>'Lebanese','country_name_ar'=>'لبنان','country_name_en'=>'Lebanon','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ليسوتي','nationality_name_en'=>'Basotho','country_name_ar'=>'ليسوتو','country_name_en'=>'Lesotho','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ليبيري','nationality_name_en'=>'Liberian','country_name_ar'=>'ليبيريا','country_name_en'=>'Liberia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ليختنشتايني','nationality_name_en'=>'Liechtensteiner','country_name_ar'=>'ليختنشتاين','country_name_en'=>'Liechtenstein','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ليتواني','nationality_name_en'=>'Lithuanian','country_name_ar'=>'ليتوانيا','country_name_en'=>'Lithuania','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'لوكسمبورغي','nationality_name_en'=>'Luxembourgish','country_name_ar'=>'لوكسمبورغ','country_name_en'=>'Luxembourg','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مدغشقري','nationality_name_en'=>'Malagasy','country_name_ar'=>'مدغشقر','country_name_en'=>'Madagascar','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مالاوي','nationality_name_en'=>'Malawian','country_name_ar'=>'مالاوي','country_name_en'=>'Malawi','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ماليزي','nationality_name_en'=>'Malaysian','country_name_ar'=>'ماليزيا','country_name_en'=>'Malaysia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مالديفي','nationality_name_en'=>'Maldivian','country_name_ar'=>'جزر المالديف','country_name_en'=>'Maldives','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مالي','nationality_name_en'=>'Malian','country_name_ar'=>'مالي','country_name_en'=>'Mali','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مالطي','nationality_name_en'=>'Maltese','country_name_ar'=>'مالطا','country_name_en'=>'Malta','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مارشالي','nationality_name_en'=>'Marshallese','country_name_ar'=>'جزر مارشال','country_name_en'=>'Marshall Islands','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'موريتاني','nationality_name_en'=>'Mauritanian','country_name_ar'=>'موريتانيا','country_name_en'=>'Mauritania','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'موريشي','nationality_name_en'=>'Mauritian','country_name_ar'=>'موريشيوس','country_name_en'=>'Mauritius','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مكسيكي','nationality_name_en'=>'Mexican','country_name_ar'=>'المكسيك','country_name_en'=>'Mexico','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ميكرونيزي','nationality_name_en'=>'Micronesian','country_name_ar'=>'ميكرونيزيا','country_name_en'=>'Micronesia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مولدوفي','nationality_name_en'=>'Moldovan','country_name_ar'=>'مولدوفا','country_name_en'=>'Moldova','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'موناكي','nationality_name_en'=>'Monégasque','country_name_ar'=>'موناكو','country_name_en'=>'Monaco','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'منغولي','nationality_name_en'=>'Mongolian','country_name_ar'=>'منغوليا','country_name_en'=>'Mongolia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مونتينيغري','nationality_name_en'=>'Montenegrin','country_name_ar'=>'الجبل الأسود','country_name_en'=>'Montenegro','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مغربي','nationality_name_en'=>'Moroccan','country_name_ar'=>'المغرب','country_name_en'=>'Morocco','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'موزمبيقي','nationality_name_en'=>'Mozambican','country_name_ar'=>'موزمبيق','country_name_en'=>'Mozambique','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ميانماري','nationality_name_en'=>'Burmese','country_name_ar'=>'ميانمار','country_name_en'=>'Myanmar','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ناميبي','nationality_name_en'=>'Namibian','country_name_ar'=>'ناميبيا','country_name_en'=>'Namibia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ناوري','nationality_name_en'=>'Nauruan','country_name_ar'=>'ناورو','country_name_en'=>'Nauru','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'نيبالي','nationality_name_en'=>'Nepalese','country_name_ar'=>'نيبال','country_name_en'=>'Nepal','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'هولندي','nationality_name_en'=>'Dutch','country_name_ar'=>'هولندا','country_name_en'=>'Netherlands','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'نيوزيلندي','nationality_name_en'=>'New Zealander','country_name_ar'=>'نيوزيلندا','country_name_en'=>'New Zealand','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'نيكاراغوي','nationality_name_en'=>'Nicaraguan','country_name_ar'=>'نيكاراغوا','country_name_en'=>'Nicaragua','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'نيجري','nationality_name_en'=>'Nigerien','country_name_ar'=>'النيجر','country_name_en'=>'Niger','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'نيجيري','nationality_name_en'=>'Nigerian','country_name_ar'=>'نيجيريا','country_name_en'=>'Nigeria','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'مقدوني','nationality_name_en'=>'Macedonian','country_name_ar'=>'مقدونيا الشمالية','country_name_en'=>'North Macedonia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'نرويجي','nationality_name_en'=>'Norwegian','country_name_ar'=>'النرويج','country_name_en'=>'Norway','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'عماني','nationality_name_en'=>'Omani','country_name_ar'=>'عمان','country_name_en'=>'Oman','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'باكستاني','nationality_name_en'=>'Pakistani','country_name_ar'=>'باكستان','country_name_en'=>'Pakistan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بالاوي','nationality_name_en'=>'Palauan','country_name_ar'=>'بالاو','country_name_en'=>'Palau','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بنمي','nationality_name_en'=>'Panamanian','country_name_ar'=>'بنما','country_name_en'=>'Panama','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بابوي','nationality_name_en'=>'Papua New Guinean','country_name_ar'=>'بابوا غينيا الجديدة','country_name_en'=>'Papua New Guinea','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'باراغواياني','nationality_name_en'=>'Paraguayan','country_name_ar'=>'باراغواي','country_name_en'=>'Paraguay','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بيروفي','nationality_name_en'=>'Peruvian','country_name_ar'=>'بيرو','country_name_en'=>'Peru','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فلبيني','nationality_name_en'=>'Filipino','country_name_ar'=>'الفلبين','country_name_en'=>'Philippines','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بولندي','nationality_name_en'=>'Polish','country_name_ar'=>'بولندا','country_name_en'=>'Poland','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'برتغالي','nationality_name_en'=>'Portuguese','country_name_ar'=>'البرتغال','country_name_en'=>'Portugal','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'قطري','nationality_name_en'=>'Qatari','country_name_ar'=>'قطر','country_name_en'=>'Qatar','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'روماني','nationality_name_en'=>'Romanian','country_name_ar'=>'رومانيا','country_name_en'=>'Romania','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'روسي','nationality_name_en'=>'Russian','country_name_ar'=>'روسيا','country_name_en'=>'Russia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'رواندي','nationality_name_en'=>'Rwandan','country_name_ar'=>'رواندا','country_name_en'=>'Rwanda','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'كيتسي','nationality_name_en'=>'Kittitian','country_name_ar'=>'سانت كيتس ونيفيس','country_name_en'=>'Saint Kitts and Nevis','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'لوسياني','nationality_name_en'=>'Saint Lucian','country_name_ar'=>'سانت لوسيا','country_name_en'=>'Saint Lucia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فنسنتي','nationality_name_en'=>'Saint Vincentian','country_name_ar'=>'سانت فنسنت والغرينادين','country_name_en'=>'Saint Vincent and the Grenadines','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ساموي','nationality_name_en'=>'Samoan','country_name_ar'=>'ساموا','country_name_en'=>'Samoa','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ماريني','nationality_name_en'=>'Sammarinese','country_name_ar'=>'سان مارينو','country_name_en'=>'San Marino','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ساوتومي','nationality_name_en'=>'Sao Tomean','country_name_ar'=>'ساو تومي وبرينسيب','country_name_en'=>'Sao Tome and Principe','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سعودي','nationality_name_en'=>'Saudi','country_name_ar'=>'المملكة العربية السعودية','country_name_en'=>'Saudi Arabia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سنغالي','nationality_name_en'=>'Senegalese','country_name_ar'=>'السنغال','country_name_en'=>'Senegal','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'صربي','nationality_name_en'=>'Serbian','country_name_ar'=>'صربيا','country_name_en'=>'Serbia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سيشيلي','nationality_name_en'=>'Seychellois','country_name_ar'=>'سيشل','country_name_en'=>'Seychelles','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سيراليوني','nationality_name_en'=>'Sierra Leonean','country_name_ar'=>'سيراليون','country_name_en'=>'Sierra Leone','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سنغافوري','nationality_name_en'=>'Singaporean','country_name_ar'=>'سنغافورة','country_name_en'=>'Singapore','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سلوفاكي','nationality_name_en'=>'Slovak','country_name_ar'=>'سلوفاكيا','country_name_en'=>'Slovakia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سلوفيني','nationality_name_en'=>'Slovenian','country_name_ar'=>'سلوفينيا','country_name_en'=>'Slovenia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سليماني','nationality_name_en'=>'Solomon Islander','country_name_ar'=>'جزر سليمان','country_name_en'=>'Solomon Islands','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'صومالي','nationality_name_en'=>'Somali','country_name_ar'=>'الصومال','country_name_en'=>'Somalia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'جنوب أفريقي','nationality_name_en'=>'South African','country_name_ar'=>'جنوب أفريقيا','country_name_en'=>'South Africa','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'جنوب سوداني','nationality_name_en'=>'South Sudanese','country_name_ar'=>'جنوب السودان','country_name_en'=>'South Sudan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إسباني','nationality_name_en'=>'Spanish','country_name_ar'=>'إسبانيا','country_name_en'=>'Spain','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سريلانكي','nationality_name_en'=>'Sri Lankan','country_name_ar'=>'سريلانكا','country_name_en'=>'Sri Lanka','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سوداني','nationality_name_en'=>'Sudanese','country_name_ar'=>'السودان','country_name_en'=>'Sudan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سورينامي','nationality_name_en'=>'Surinamese','country_name_ar'=>'سورينام','country_name_en'=>'Suriname','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سويدي','nationality_name_en'=>'Swedish','country_name_ar'=>'السويد','country_name_en'=>'Sweden','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سويسري','nationality_name_en'=>'Swiss','country_name_ar'=>'سويسرا','country_name_en'=>'Switzerland','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'سوري','nationality_name_en'=>'Syrian','country_name_ar'=>'سوريا','country_name_en'=>'Syria','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تايواني','nationality_name_en'=>'Taiwanese','country_name_ar'=>'تايوان','country_name_en'=>'Taiwan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'طاجيكي','nationality_name_en'=>'Tajik','country_name_ar'=>'طاجيكستان','country_name_en'=>'Tajikistan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تنزاني','nationality_name_en'=>'Tanzanian','country_name_ar'=>'تنزانيا','country_name_en'=>'Tanzania','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تايلاندي','nationality_name_en'=>'Thai','country_name_ar'=>'تايلاند','country_name_en'=>'Thailand','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تيموري','nationality_name_en'=>'Timorese','country_name_ar'=>'تيمور الشرقية','country_name_en'=>'Timor-Leste','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'توغولي','nationality_name_en'=>'Togolese','country_name_ar'=>'توغو','country_name_en'=>'Togo','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تونغي','nationality_name_en'=>'Tongan','country_name_ar'=>'تونغا','country_name_en'=>'Tonga','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'ترينيدادي','nationality_name_en'=>'Trinidadian','country_name_ar'=>'ترينيداد وتوباغو','country_name_en'=>'Trinidad and Tobago','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تونسي','nationality_name_en'=>'Tunisian','country_name_ar'=>'تونس','country_name_en'=>'Tunisia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تركي','nationality_name_en'=>'Turkish','country_name_ar'=>'تركيا','country_name_en'=>'Turkey','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'تركماني','nationality_name_en'=>'Turkmen','country_name_ar'=>'تركمانستان','country_name_en'=>'Turkmenistan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'توفالي','nationality_name_en'=>'Tuvaluan','country_name_ar'=>'توفالو','country_name_en'=>'Tuvalu','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أوغندي','nationality_name_en'=>'Ugandan','country_name_ar'=>'أوغندا','country_name_en'=>'Uganda','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أوكراني','nationality_name_en'=>'Ukrainian','country_name_ar'=>'أوكرانيا','country_name_en'=>'Ukraine','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'إماراتي','nationality_name_en'=>'Emirati','country_name_ar'=>'الإمارات العربية المتحدة','country_name_en'=>'United Arab Emirates','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'بريطاني','nationality_name_en'=>'British','country_name_ar'=>'المملكة المتحدة','country_name_en'=>'United Kingdom','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أمريكي','nationality_name_en'=>'American','country_name_ar'=>'الولايات المتحدة','country_name_en'=>'United States','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أوروغوايي','nationality_name_en'=>'Uruguayan','country_name_ar'=>'الأوروغواي','country_name_en'=>'Uruguay','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'أوزبكي','nationality_name_en'=>'Uzbek','country_name_ar'=>'أوزبكستان','country_name_en'=>'Uzbekistan','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فانواتي','nationality_name_en'=>'Ni-Vanuatu','country_name_ar'=>'فانواتو','country_name_en'=>'Vanuatu','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فاتيكاني','nationality_name_en'=>'Vatican','country_name_ar'=>'الفاتيكان','country_name_en'=>'Vatican City','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فنزويلي','nationality_name_en'=>'Venezuelan','country_name_ar'=>'فنزويلا','country_name_en'=>'Venezuela','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'فيتنامي','nationality_name_en'=>'Vietnamese','country_name_ar'=>'فيتنام','country_name_en'=>'Vietnam','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'يمني','nationality_name_en'=>'Yemeni','country_name_ar'=>'اليمن','country_name_en'=>'Yemen','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'زامبي','nationality_name_en'=>'Zambian','country_name_ar'=>'زامبيا','country_name_en'=>'Zambia','created_at'=>$now,'updated_at'=>$now],
            ['nationality_name_ar'=>'زيمبابوي','nationality_name_en'=>'Zimbabwean','country_name_ar'=>'زيمبابوي','country_name_en'=>'Zimbabwe','created_at'=>$now,'updated_at'=>$now],
        ];

        DB::table('countries')->insert($countries);
    }
}
